### ISSUE TITLE
Does the plugin assume the angular module is named "app"?

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman-angular#2]
Just heard from @markbates that the plugin requires the app is named "app"? What's doing this and can we alleviate that? Worst case, can we expose a configuration?

(If we need to expose a configuration, it means we have to play this issue in core: https://github.com/linemanjs/lineman/issues/174 )

**Comment by Foxandxss** [comment]
If we are talking about this plugin (and not the example template), the only part that talks about `app` is the plugin that compiles the [templates](https://github.com/linemanjs/lineman-angular/blob/master/config/plugins/ngtemplates.coffee)

Concretely, it accepts a `module` parameter IIRC that will change `app` to something different. We could expose that for sure.

There is nothing else that puts a name to the app.

**Comment by searls** [comment]
Are you saying that grunt-ngtemplates is assuming the module is named app? I don't see anything in our config that locks down to app except as a base directory, which of course is assumed for all lineman projects

**Comment by searls** [comment]
Answered my own question, it's not us it's actually [grunt-angular-templates](https://github.com/ericclemmons/grunt-angular-templates) making that assumption

```
    ngtemplates: {
      options: {
        module: "foo"
      }
    }
```

Was a successful way to override it. I imagine if your app has multiple modules, you'd need to duplicate the setup across multiple targets (yuck)

**Comment by Foxandxss** [comment]
No, not assuming, it just generates a new `angular-templates.js` file which starts like:

``` javascript
angular.module("app").run(["$templateCache", function($templateCache) {
```

If we put the `module` option in the config, we can achieve:

``` javascript
angular.module("Myapp").run(["$templateCache", function($templateCache) {
```

Here is the new config:

```
ngtemplates: {
    app: {
        options: {
          base: "app/templates",
          module: 'Myapp',
        },
        src: "app/templates/**/*.html",
        dest: "<%= files.ngtemplates.dest %>"
      }
 }
```

You just need to make module configurable in some point.

Apart from this, nothing is making this app be called `app`. The directory name is well, kinda fixed but that doesn't affect angular itself.

I guess that with that @markbates should be happy.

**Comment by Foxandxss** [comment]
Uhm you were fast enough.

I have multiple modules in my apps, I just stick all modules to one module.

Anyway, that personalization is not our problem, the end user should configure it in the way it wants to.

**Comment by searls** [comment]
Right, but because we're layering an abstraction/indirection on top of the underlying grunt task, it's up to us to either make its assumptions/limitations clear to users or to simplify them ourselves.

I just brought called it out now [in the template project](https://github.com/linemanjs/lineman-angular-template/blob/master/config/application.js#L17-L24), but think we should also probably add a note to this plugin's README. Also strikes me that we'll need to start documenting the plugins well enough to include them in the linemanjs.com docs.

**Comment by searls** [comment]
Closing now that I've documented it.

**Comment by Foxandxss** [comment]
:+1:
